// ignore_for_file: file_names, constant_identifier_names

const Map<String, String> Lithuanian = {
  "Choose the language": "Pasirinkite kalbą",
  "search language": "paieškos kalba",
  "Continue": "Tęsti",
  "Already have account?": "Jau turite paskyrą?",
  "Log In": "Prisijungti",
  "Sign up": "Registruotis",
  "Don’t have account? ": "Neturite paskyros? ",
  "Successfully create your account": "Sėkmingai susikurkite paskyrą",
  "successfully create your account now enjoy our apps": "sėkmingai susikurkite paskyrą, dabar mėgaukitės mūsų programomis",
  "Create New Password": "Sukurti naują slaptažodį",
  "remember me": "Prisimink mane",
  "Forgot Password": "Pamiršote slaptažodį",
  "Please enter your valid email ID. we will send you 6-digit code to verify your account.": "Įveskite galiojantį el. pašto ID. atsiųsime jums 6 skaitmenų kodą paskyrai patvirtinti.",
  "User name": "Vartotojo vardas",
  "Confirm password": "Patvirtinti slaptažodį",
  "Forget Password?": "Pamiršti slaptažodį?",
  "Privacy Policy": "Privatumo politika",
  "Change Password": "Pakeisti slaptažodį",
  "Delete Account": "Ištrinti paskyrą",
  "enter current password": "Įveskite dabartinį slaptažodį",
  "enter new password": "Įveskite naują slaptažodį",
  "Confirm new password": "Patvirtinti naują slaptažodį",
  "Password": "Slaptažodis",
  "Are you sure you want to Delete Account?": "Ar tikrai norite ištrinti paskyrą?",
  "Are you sure want to Log Out?": "Ar tikrai norite Atsijungti?",
  "Are you sure want to Exit?": "Ar tikrai norite išeiti?",
  "Contact us": "Susisiekite su mumis",
  "Name": "vardas",
  "e-mail": "El. paštas",
  "Description": "apibūdinimas",
   "Send": "Siųsti",
  "Yes": "Taip",
  "No": "Ne",
  "skip": "praleisti",
  "See Every Detail,\n Full Screen at Your Fingertips": "Peržiūrėkite kiekvieną detalę,\n po ranka pasiekiamas visas ekranas",
  "Easily Share Images &\n Videos": "Lengvai bendrinkite vaizdus ir\n vaizdo įrašus",
  "Click, Secure,Download\n Images & Videos easily": "Spustelėkite, Apsaugokite, Atsisiųskite\n Vaizdus ir vaizdo įrašus lengvai",
  "Next": "Kitas",
  "Get Started": "Pradėti",
  "Login / Logout": "Prisijungti / Atsijungti",
  "Logout": "Atsijungti",
  "FAQ": "DUK",
  "Settings": "Nustatymai",
  "Favourites": "Mėgstamiausi",
  "Home": "Namai",
  "filuet": "filė",
  "Designed by": "Suprojektuotas",
  "Select": "Pasirinkti",
  "Success": "Sėkmingai",
  "Error": "Klaida",
  "My Boards": "Mano lentos",
  "Motivation": "Motyvacija",
  "My Folder": "Mano aplankas",
  "Challenge": "Iššūkis",
  "Weekend": "Savaitgalis",
  "Holiday": "Svētki",
  "Tasty": "Skanus",
  "Events": "Įvykiai",
  "Language": "Kalba",
  "Cancel": "Atšaukti",
  "Confirm": "Patvirtinti",
  "Image Selected": "Pasirinktas vaizdas",
  "English": "Anglų",
  "Latvian": "Latvių",
  "Estonian": "Estų",
  "Lithuanian": "Lietuvių",
  "Email can not be empty": "El. pašto laukas negali būti tuščias",
  "Invalid email format": "Netinkamas el. pašto formatas",
  "Invalid username/password!": "Netinkamas vartotojo vardas / slaptažodis!",
  "Please enter your current password.": "Įveskite dabartinį slaptažodį.",
  "Please enter your password.": "Prašome įvesti savo slaptažodį.",
  "Password must be at least 8 characters": "Slaptažodį turi sudaryti bent 8 simboliai",
  "Please enter your Confirm password.": "Įveskite patvirtinimo slaptažodį.",
  "Passwords do not match.": "Slaptažodžiai nesutampa.",
  "This account is already exits!": "Ši paskyra jau baigta!",
  "Please enter your User name": "Įveskite savo vartotojo vardą",
  "Password Reset Email Sent": "Slaptažodžio nustatymo iš naujo el. laiškas išsiųstas",
  "Check your email for instructions to reset your password.": "Patikrinkite el. paštą instrukcijų, kaip iš naujo nustatyti slaptažodį.",
  "Please log in before delete Account.": "Prieš ištrindami paskyrą prisijunkite.",
  "Please log in before resetting your password.": "Prieš nustatydami slaptažodį iš naujo, prisijunkite.",
  "View Images":"Peržiūrėti vaizdus",
  "My Wallpaper":"Mano tapetai",
  "Or":"Arba",
  "This is main category" : "Tai pagrindinė kategorija",
  "Click main category for sub category." : "Spustelėkite pagrindinę kategoriją, kad pamatytumėte subkategoriją.",

  "Click here to open main category's images" : "Spustelėkite čia, kad atidarytumėte pagrindinės kategorijos vaizdus",
  "This is main category title" : "Tai yra pagrindinės kategorijos pavadinimas",
  "Click here to open sub category's images" : "Spustelėkite čia, kad atidarytumėte subkategorijų vaizdus",
  "No data found" : "Duomenų nerasta",

  "Just another magic day!":"Tiesiog dar viena stebuklinga diena!",
  "Future depends on what you do today!":"Ateitis priklauso nuo to, ką veiksi šiandien!",
  "Can we start the weekend again? I was not ready!":"Ar galime vėl pradėti savaitgalį? Aš nebuvau pasiruošęs!",
  "Don’t limit your challenges. Challenge your limits.":"Neribokite savo iššūkių. Mesk iššūkį savo riboms.",
  "Russian":"Rusų",
  "Telephone":"Telefonas",
  //"Tel":"Tel",
  "Tel":"Telegram",
  "Images are downloaded successfully":"Vaizdai atsisiųsti sėkmingai",
  "Okay":"Gerai"
};
