const Map<String, String> Lithuanian = {
  "Choose The Language": "Pasirinkite kalbą",
  "search language": "paieškos kalba",
  "Continue": "Tęsti",
  "My Boards": "Mano lentos",
  "Motivation": "Motyvacija",
  "My Folder": "Mano aplankas",
  "Challenge": "Iššūkis",
  "Weekend": "Savaitgalis",
  "Holidays": "Atostogos",
  "Tasty": "Skanus",
  "Events": "Įvykiai",
  "Language": "Kalba",
  "Cancel": "Atšaukti",
  "Confirm": "Patvirtinti",
  "Image Selected": "Pasirinktas vaizdas",
  "English": "Anglų",
  "Latvian": "latvių",
  "Estonian": "estiškas",
  "Lithuanian": "Lietuvis",
  "Error":"Klaida",
  "Success":"Sėkmė",
  "Select":"Pasirinkite"
};
