// ignore_for_file: file_names, constant_identifier_names

const Map<String, String> Russian = {
  "Choose the language":"Выберите язык",
  "search language":"язык поиска",
  "Continue":"Продолжить",
  "Already have account?":"Уже есть аккаунт?",
  "Log In":"Авторизоваться",
  "Sign up":"Зарегистрироваться",
  "Don’t have account? ":"Нет аккаунта? ",
  "Successfully create your account":"Успешно создайте свою учетную запись",
  "successfully create your account now enjoy our apps":"успешно создайте свою учетную запись, теперь наслаждайтесь нашими приложениями",
  "Create New Password":"Создать новый пароль",
  "remember me":"запомнить меня",
  "Forgot Password":"Забыли пароль",
  "Please enter your valid email ID. we will send you 6-digit code to verify your account.":"Пожалуйста, введите свой действительный адрес электронной почты. мы вышлем вам 6-значный код для подтверждения вашей учетной записи.",
  "User name":"Имя пользователя",
  "Confirm password":"Подтвердите пароль",
  "Forget Password?":"Забыть пароль?",
  "Privacy Policy":"политика конфиденциальности",
  "Change Password":"Изменить пароль",
  "Delete Account":"Удалить аккаунт",
  "enter current password":"введите текущий пароль",
  "enter new password":"Введите новый пароль",
  "Confirm new password":"Подтвердите новый пароль",
  "Password":"Пароль",
  "Are you sure you want to Delete Account?":"Вы уверены, что хотите удалить аккаунт?",
  "Are you sure want to Log Out?":"Вы уверены, что хотите выйти?",
  "Are you sure want to Exit?":"Вы действительно хотите выйти?",
  "Contact us":"Связаться с нами",
  "Name":"Имя",
  "e-mail":"Э-почта",
  "Description":"Описание",
  "Send":"Отправлять",
  "Yes":"Да",
  "No":"Нет",
  "skip":"пропускать",
  "See Every Detail,\n Full Screen at Your Fingertips":"Просматривайте каждую деталь\n, полноэкранный режим всегда у вас под рукой",
  "Easily Share Images &\n Videos":"Легко делитесь изображениями",
  "Click, Secure,Download\n Images & Videos easily":"Нажмите, защитите, загрузите\n изображения.",
  "Next":"Следующий",
  "Get Started":"Начать",
  "Login / Logout":"Вход/Выход",
  "Logout":"Выход",
  "FAQ":"Часто задаваемые вопросы",
  "Settings":"Настройки",
  "Favourites":"Избранное",
  "Home":"Дом",
  "filuet":"филе",
  "Designed by":"Разработано",
  "Select":"Выбрать",
  "Success":"Успешно",
  "Error":"Ошибка",
  "My Boards":"Мои доски",
  "Motivation":"Мотивация",
  "My Folder":"Моя папка",
  "Challenge":"Испытание",
  "Weekend":"Выходные",
  "Holiday":"Праздничный день",
  "Tasty":"Вкусный",
  "Events":"События",
  "Email can not be empty":"Электронная почта не может быть пустой",
  "Language":"Язык",
  "Cancel":"Отмена",
  "Confirm":"Подтверждать",
  "Image Selected":"Изображение выбрано",
  "English":"Английский",
  "Latvian":"Латышский",
  "Estonian":"Эстонский",
  "Lithuanian":"Литовский",
  "Check your email for instructions to reset your password.":"Проверьте свою электронную почту на наличие инструкций по сбросу пароля.",
  "Password Reset Email Sent":"Письмо для сброса пароля отправлено",
  "Passwords do not match.":"Пароли не совпадают.",
  "Please enter your Confirm password.":"Пожалуйста, введите пароль для подтверждения.",
  "Password must be at least 8 characters":"Пароль должен быть не менее 8 символов",
  "Please enter your password.":"Пожалуйста введите ваш пароль.",
  "Invalid username/password!":"Неверное имя пользователя / пароль!",
  "Invalid email format":"Неверный формат электронной почты",
  "Please enter your current password.":"Пожалуйста, введите ваш текущий пароль.",
  "This account is already exits!":"Этот аккаунт уже закрыт!",
  "Please enter your User name":"Пожалуйста, введите Ваш логин",
  "Please log in before delete Account.":"Пожалуйста, войдите в систему, прежде чем удалять учетную запись.",
  "Please log in before resetting your password.":"Пожалуйста, войдите в систему перед сбросом пароля.",
  "View Images":"Просмотр изображений",
  "My Wallpaper":"Мои обои",
  "Or":"Или",
  "This is main category" :"Это основная категория",
  "Click main category for sub category.":"Нажмите основную категорию для просмотра подкатегории.",
  "Click here to open main category's images" :"НfSucажмите здесь, чтобы открыть изображения основной категории",
  "This is main category title" : "Это название основной категории",
  "Click here to open sub category's images" :"Нажмите здесь, чтобы открыть изображения подкатегории",
  "No data found" :"Данные не найдены",
  "Just another magic day!":"Просто еще один волшебный день!",
  "Future depends on what you do today!":"Будущее зависит от того, что вы делаете сегодня!",
  "Can we start the weekend again? I was not ready!":"Можем ли мы начать выходные снова? Я не был готов!",
  "Don’t limit your challenges. Challenge your limits.":"Не ограничивайте свои задачи. Бросьте вызов своим ограничениям.",
  "Russian":"Русский",
  "Telephone":"Телефон",
  //"Tel":"Тел",
  "Tel":"Telegram",
  "Images are downloaded successfully":"Изображения успешно загружены",
  "Okay":"Хорошо"
};
