const Map<String, String> Estonian = {
  "Choose The Language": "Vali keel",
  "search language": "otsingu keel",
  "Continue": "Jätka",
  "My Boards": "Minu tahvlid",
  "Motivation": "Motivatsioon",
  "My Folder": "Minu kaust",
  "Challenge": "Challenge",
  "Weekend": "Nädalalõpp",
  "Holidays": "Pühad",
  "Tasty": "Maitsev",
  "Events": "Sündmused",
  "Language": "Keel",
  "Cancel": "Tühista",
  "Confirm": "Kinnita",
  "Image Selected": "Pilt valitud",
  "English": "Inglise",
  "Latvian": "läti",
  "Estonian": "eestlane",
  "Lithuanian": "Leedu",
  "Error":"Viga",
  "Success":"Edu",
  "Select":"Valige"
};
