const Map<String, String> Estonian = {
  "Choose The Language": "Vali keel",
  "search language": "otsingu keel",
  "Continue": "Jätka",
  "Already have account?": "Kas teil on juba konto?",
  "Log In": "Logi sisse",
  "Sign up": "Registreeri",
  "Don’t have account? ": "Kas teil pole kontot? ",
  "Successfully create your account": "Looge oma konto edukalt",
  "successfully create your account now enjoy our apps": "looge oma konto edukalt ja nautige nüüd meie rakendusi",
  "Create New Password": "Loo uus parool",
  "remember me": "mäleta mind",
  "Forgot Password": "Unustasid parooli",
  "Please enter your valid email ID. we will send you 6-digit code to verify your account.": "Sisestage oma kehtiv e-posti ID. saadame teile konto kinnitamiseks 6-kohalise koodi.",
  "User name": "Kasutajanimi",
  "Confirm password": "Kinnita salasõna",
  "Forget Password?": "Unustasite parooli?",
  "Privacy Policy": "Privaatsuspoliitika",
  "Change Password": "Muuda salasõna",
  "Delete Account": "Kustuta konto",
  "enter current password": "sisestage praegune parool",
  "enter new password": "sisestage uus parool",
  "Confirm new password": "Kinnita Uus salasõna",
  "Password": "Parool",
  "Are you sure you want to Delete Account?": "Kas olete kindel, et soovite konto kustutada?",
  "Are you sure want to Log Out?": "Kas soovite kindlasti välja logida?",
  "Are you sure want to Exit?": "Kas soovite kindlasti väljuda?",
  "Contact Us": "Võta meiega ühendust",
  "Name": "Nimi",
  "Email ID": "E-kirja ID",
  "Description": "Kirjeldus",
  "Send": "Saada",
  "Yes": "Jah",
  "No": "Ei",
  "skip": "vahele jätma",
  "See Every Detail,\n Full Screen at Your Fingertips": "Vaadake iga detaili,\n teie käeulatuses täisekraan",
  "Easily Share Images &\n Videos": "Jagage hõlpsalt pilte ja\n videoid",
  "Click, Secure,Download\n Images & Videos easily": "Klõpsake, kaitske, laadige alla\n Pildid ja videod lihtsalt",
  "Next": "Edasi",
  "Get Started": "Alustama",
  "Login / Logout": "Logi sisse / Välja",
  "FAQ": "KKK",
  "Settings": "Seaded",
  "Favourite": "Lemmik",
  "Home": "Kodu",
  "filuet": "filuett",
  "Designed by": "Disainitud",
  "Select": "Valige",
  "Success": "Edu",
  "Error": "Viga",
  "My Boards": "Minu tahvlid",
  "Motivation": "Motivacija",
  "My Folder": "Minu kaust",
  "Challenge": "Väljakutse",
  "Weekend": "Nädalavahetus",
  "Holiday": "Puhkus",
  "Tasty": "Maitsev",
  "Events": "Sündmused",
  "Language": "Keel",
  "Cancel": "Tühista",
  "Confirm": "Kinnita",
  "Image Selected": "Pilt valitud",
  "English": "Inglise",
  "Latvian": "läti",
  "Estonian": "eestlane",
  "Lithuanian": "Leedu",
  "Please enter your Confirm password.": "Palun sisesta oma Kinnita parool.",
  "Password must be at least 8 characters": "Parool peab koosnema vähemalt 8 tähemärgist",
  "Email can not be empty": "E-posti väli ei tohi olla tühi",
  "Invalid email format": "Kehtetu meilivorming",
  "Invalid username/password!": "Vale kasutajanimi / parool!",
  "Please enter your current password.": "Palun sisesta oma praegune parool.",
  "Please enter your password.": "Palun sisesta oma salasõna.",
  "Passwords do not match.": "Paroolid ei kattu.",
  "This account is already exits!": "See konto on juba väljunud!",
  "Please enter your User name": "Palun sisesta oma kasutajanimi",
  "Password Reset Email Sent": "Parooli lähtestamise e-kiri saadetud",
  "Check your email for instructions to reset your password.": "Parooli lähtestamise juhiste saamiseks kontrollige oma meili.",
  "Please log in before delete Account.": "Enne konto kustutamist logige sisse.",
  "Please log in before resetting your password.": "Enne parooli lähtestamist logige sisse.",
  "View Images":"Vaata pilte",
  "My Wallpaper":"Minu tapeet",
  "Or":"Või",
  "This is main category" : "This is main category",

  "Click here to open main category's images" : "Põhikategooria piltide avamiseks klõpsake siin",
  "This is main category title" : "See on põhikategooria pealkiri",
  "Click here to open sub category's images" : "Alamkategooria piltide avamiseks klõpsake siin",
  "No data found" : "Andmeid ei leitud",

  "Just another magic day!":"Lihtsalt üks maagiline päev!",
  "Future depends on what you do today!":"Tulevik sõltub sellest, mida teete täna!",
  "Can we start the weekend again? I was not ready!":"Kas saame nädalavahetust uuesti alustada? Ma ei olnud valmis!",
  "Don’t limit your challenges. Challenge your limits.":"Ärge piirake oma väljakutseid. Sea oma piirid proovile.",
  "Russian":"vene keel",
  "Phone NO":"Telefoni nr",
  "Telegram":"Telegramm",
};
