const Map<String, String> English = {
  "Choose The Language": "Choose The Language",
  "search language": "search language",
  "Continue": "Continue",
  "Already have account?": "Already have account?",
  "Log In": "Log In",
  "Sign up": "Sign up",
  "Don’t have account? ": "Don’t have account? ",
  "Successfully create your account": "Successfully create your account",
  "successfully create your account now enjoy our apps": "successfully create your account now enjoy our apps",
  "Create New Password": "Create New Password",
  "remember me": "remember me",
  "Forgot Password": "Forgot Password",
  "Please enter your valid email ID. we will send you 6-digit code to verify your account.": "Please enter your valid email ID. we will send you 6-digit code to verify your account.",
  "User name": "User name",
  "Confirm password": "Confirm password",
  "Forget Password?": "Forget Password?",
  "Privacy Policy": "Privacy Policy",
  "Change Password": "Change Password",
  "Delete Account": "Delete Account",
  "enter current password": "enter current password",
  "enter new password": "enter new password",
  "Confirm new password": "Confirm new password",
  "Password": "Password",
  "Are you sure you want to Delete Account?": "Are you sure you want to Delete Account?",
  "Are you sure want to Log Out?": "Are you sure want to Log Out?",
  "Are you sure want to Exit?": "Are you sure want to Exit?",
  "Contact Us": "Contact Us",
  "Name": "Name",
  "Email ID": "Email ID",
  "Description": "Description",
  "Send": "Send",
  "Yes": "Yes",
  "No": "No",
  "skip": "skip",
  "See Every Detail,\n Full Screen at Your Fingertips": "See Every Detail,\n Full Screen at Your Fingertips",
  "Easily Share Images &\n Videos": "Easily Share Images &\n Videos",
  "Click, Secure,Download\n Images & Videos easily": "Click, Secure,Download\n Images & Videos easily",
  "Next": "Next",
  "Get Started": "Get Started",
  "Login / Logout": "Login / Logout",
  "FAQ": "FAQ",
  "Settings": "Settings",
  "Favourite": "Favourite",
  "Home": "Home",
  "filuet": "filuet",
  "Designed by": "Designed by",
  "Select": "Select",
  "Success": "Success",
  "Error": "Error",
  "My Boards": "My Boards",
  "Motivation": "Motivation",
  "My Folder": "My Folder",
  "Challenge": "Challenge",
  "Weekend": "Weekend",
  "Holidays": "Holidays",
  "Tasty": "Tasty",
  "Events": "Events",
  "Email can not be empty": "Email can not be empty",
  "Language": "Language",
  "Cancel": "Cancel",
  "Confirm": "Confirm",
  "Image Selected": "Image Selected",
  "English": "English",
  "Latvian": "Latvian",
  "Estonian": "Estonian",
  "Lithuanian": "Lithuanian",
  "Check your email for instructions to reset your password.": "Check your email for instructions to reset your password.",
  "Password Reset Email Sent": "Password Reset Email Sent",
  "Passwords do not match.": "Passwords do not match.",
  "Please enter your Confirm password.": "Please enter your Confirm password.",
  "Password must be at least 8 characters": "Password must be at least 8 characters",
  "Please enter your password.": "Please enter your password.",
  "Invalid username/password!": "Invalid username/password!",
  "Invalid email format": "Invalid email format",
  "Please enter your current password.": "Please enter your current password.",
  "This account is already exits!": "This account is already exits!",
  "Please enter your User name": "Please enter your User name",
  "Please log in before delete Account.": "Please log in before delete Account.",
  "Please log in before resetting your password.": "Please log in before resetting your password.",
  "View Images":"View Images",
  "My Wallpaper":"My Wallpaper",
  "Or":"Or",
  "This is main category" : "This is main category",
  "Click main category for sub category." : "Click main category for sub category.",

  "Click here to open main category's images" : "Click here to open main category's images",
  "This is main category title" : "This is main category title",
  "Click here to open sub category's images" : "Click here to open sub category's images",
};
