const Map<String, String> English = {
  "Choose The Language": "Choose The Language",
  "search language": "search language",
  "Continue": "Continue",
  "Already have account?": "Already have account?",
  "Log In": "Log In",
  "Sign up": "Sign up",
  "Don’t have account? ": "Don’t have account? ",
  "Successfully create your account": "Successfully create your account",
  "My Boards": "My Boards",
  "Motivation": "Motivation",
  "My Folder": "My Folder",
  "Challenge": "Challenge",
  "Weekend": "Weekend",
  "Holidays": "Holidays",
  "Tasty": "Tasty",
  "Events": "Events",
  "Language": "Language",
  "Cancel": "Cancel",
  "Confirm": "Confirm",
  "Image Selected": "Image Selected",
  "English": "English",
  "Latvian": "Latvian",
  "Estonian": "Estonian",
  "Lithuanian": "Lithuanian",
  "Error":"Error",
  "Success":"Success",
  "Select":"Select",
  "Designed by":"Designed by",
  "filuet":"filuet",
};
