const Map<String, String> Latvian = {
  "Choose The Language": "Izvēlieties valodu",
  "search language": "meklēšanas valoda",
  "Continue": "Turpināt",
  "Already have account?": "Vai jums jau ir konts?",
  "Log In": "Pieslēgties",
  "Sign up": "Pierakstīties",
  "Don’t have account? ": "Vai jums nav konta? ",
  "Successfully create your account": "Veiksmīgi izveidojiet savu kontu",
  "My Boards": "Mani dēļi",
  "Motivation": "Motivācija",
  "My Folder": "Mana mape",
  "Challenge": "Izaicinājums",
  "Weekend": "Nedēļas nogale",
  "Holidays": "Brīvdienas",
  "Tasty": "Garšīgs",
  "Events": "Notikumi",

  "Language": "Valoda",
  "Cancel": "Atcelt",
  "Confirm": "Apstiprināt",

  "Image Selected": "Atlasīts attēls",
  "English": "Angļu",
  "Latvian": "latvietis",
  "Estonian": "igauņu",
  "Lithuanian": "lietuviešu",
  "Error":"Kļūda",
  "success":"Panākumi",
  "Select":"Izvēlieties",
  "Designed by":"Izstrādājis",
  "filuet":"filuet",
};