const Map<String, String> Latvian = {
  "Choose The Language": "Izvēlieties valodu",
  "search language": "meklēšanas valoda",
  "Continue": "Turpināt",
  "Already have account?": "Vai jums jau ir konts?",
  "Log In": "Pieslēgties",
  "Sign up": "Pierakstīties",
  "Don’t have account? ": "Vai jums nav konta? ",
  "Successfully create your account": "Veiksmīgi izveidojiet savu kontu",
  "successfully create your account now enjoy our apps": "veiksmīgi izveidojiet savu kontu, tagad izbaudiet mūsu lietotnes",
  "Create New Password": "Izveidot jaunu paroli",
  "remember me": "atceries mani",
  "Forgot Password": "Aizmirsi paroli",
  "Please enter your valid email ID. we will send you 6-digit code to verify your account.": "Lūdzu, ievadiet savu derīgo e-pasta ID. mēs nosūtīsim jums 6 ciparu kodu, lai verificētu jūsu kontu.",
  "User name": "Lietotājvārds",
  "Confirm password": "Apstipriniet paroli",
  "Forget Password?": "Aizmirsāt paroli?",
  "Privacy Policy": "Privātuma politika",
  "Change Password": "Mainīt paroli",
  "Delete Account": "Dzēst kontu",
  "enter current password": "ievadiet pašreizējo paroli",
  "enter new password": "ievadiet jaunu paroli",
  "Confirm new password": "Apstipriniet jauno paroli",
  "Password": "Parole",
  "Are you sure you want to Delete Account?": "Vai tiešām vēlaties dzēst kontu?",
  "Are you sure want to Log Out?": "Vai tiešām vēlaties atteikties?",
  "Are you sure want to Exit?": "Vai tiešām vēlaties iziet?",
  "Contact Us": "Sazinies ar mums",
  "Name": "Vārds",
  "Email ID": "E-pasta ID",
  "Description": "Apraksts",
  "Send": "Sūtīt",
  "Yes": "Jā",
  "No": "Nē",
  "skip": "izlaist",
  "See Every Detail,\n Full Screen at Your Fingertips": "Skatiet katru detaļu,\n pilnekrāna ekrāns jūsu rokās",
  "Easily Share Images &\n Videos": "Ērti kopīgojiet attēlus un\n video",
  "Click, Secure,Download\n Images & Videos easily": "Noklikšķiniet, Nodrošiniet, Lejupielādējiet\n Ērti attēlus un videoklipus",
  "Next": "Nākamais",
  "Get Started": "Sāc",
  "Login / Logout": "Pieteikties / Atteikties",
  "FAQ": "FAQ",
  "Settings": "Iestatījumi",
  "Favourite": "Mīļākais",
  "Home": "Mājas",
  "filuet": "filuets",
  "Designed by": "Projektējis",
  "Select": "Izvēlieties",
  "Success": "Panākumi",
  "Error": "Kļūda",
  "My Boards": "Mani dēļi",
  "Motivation": "Motivācija",
  "My Folder": "Mana mape",
  "Challenge": "Izaicinājums",
  "Weekend": "Nedēļas nogale",
  "Holidays": "Brīvdienas",
  "Tasty": "Garšīgs",
  "Events": "Notikumi",

  "Language": "Valoda",
  "Cancel": "Atcelt",
  "Confirm": "Apstiprināt",

  "Image Selected": "Atlasīts attēls",
  "English": "Angļu",
  "Latvian": "latvietis",
  "Estonian": "igauņu",
  "Lithuanian": "lietuviešu",
  "success":"Panākumi",
  "Email can not be empty": "E-pasta lauks nedrīkst būt tukšs",
  "Invalid email format": "Nederīgs e-pasta formāts",
  "Invalid username/password!": "Nepareizs lietotājvārds / parole!",
  "Please enter your current password.": "Lūdzu, ievadiet savu pašreizējo paroli.",
  "Please enter your password.": "Lūdzu ievadiet savu paroli.",
  "Password must be at least 8 characters": "Parolei jābūt vismaz 8 rakstzīmēm",
  "Please enter your Confirm password.": "Lūdzu, ievadiet savu Apstiprināt paroli.",
  "Passwords do not match.": "Paroles nesakrīt.",
  "This account is already exits!": "Šis konts jau ir iziets!",
  "Please enter your User name": "Lūdzu, ievadiet savu lietotājvārdu",
  "Password Reset Email Sent": "Paroles atiestatīšanas e-pasts ir nosūtīts",
  "Check your email for instructions to reset your password.": "Norādījumus paroles atiestatīšanai skatiet savā e-pastā.",
  "Please log in before delete Account.": "Lūdzu, piesakieties pirms konta dzēšanas.",
  "Please log in before resetting your password.": "Lūdzu, piesakieties pirms paroles atiestatīšanas.",
  "View Images":"Skatīt attēlus",
  "My Wallpaper":"Mana fona tapete",
  "Or":"Or",
  "This is main category" : "Šī ir galvenā kategorija",
  "Click main category for sub category." : "Noklikšķiniet uz galvenās kategorijas, lai atvērtu apakškategoriju.",

  "Click here to open main category's images" : "Noklikšķiniet šeit, lai atvērtu galvenās kategorijas attēlus",
  "This is main category title" : "Šis ir galvenās kategorijas nosaukums",
  "Click here to open sub category's images" : "Noklikšķiniet šeit, lai atvērtu apakškategorijas attēlus",
};